# Site settings
title: Terren Krietzman
email: tkrietzman@gmail.com
description: > # My personal website.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://tkrietzman.com" # the base hostname & protocol for your site 
github_username:  tkrietzman
pygments: true

# Build settings
markdown: kramdown
